version: "3"
services:
  mongo:
    image: mongo:latest
    hostname: localhost
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo

  webserver:
    build : ./webserver
    ports:
      - 5000:5000
    depends_on:
      - mongo-seed