version: "3"
services:
  mongodb:
    image: mongo:latest
    hostname: localhost
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    environment:
      - MONGO_INITDB_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  webserver:
    build : ./webserver
    ports:
      - 5000:5000
    depends_on:
      - mongo-seed
    links:
      - mongodb
    environment: 
      - MONGO_INITDB_HOST=mongodb
      - MONGO_INITDB_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - PYTHONUNBUFFERED=1